### PR TITLE
Clarify Python features will be supported

### PR DESCRIPTION
**Pull request by Garrett-R**
This is following a suggestion by @Spitfire1900 here: https://github.com/google/yapf/pull/1179#issuecomment-1838892837.

This relates to #1170.

### CODE REVIEW

**Comment by Spitfire1900** [comment]
👍🏻

**Comment by Garrett-R** [comment]
(will sign CLA)

**Comment by Garrett-R** [comment]
Ok CLA signed, so CI is passing

**Comment by Spitfire1900** [comment]
@bwendling

**Review by bwendling — APPROVED** [review]

**Pull request merged**
