### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by hugovk**
And updates for lower Python 3.x supported version.

### CODE REVIEW

**Comment by gwelymernans** [comment]
Thanks! Please add an update in CHANGELOG.

**Comment by hugovk** [comment]
CHANGELOG updated!

**Comment by wookayin** [comment]
The current (master) version of yapf still does not support 3.10 syntax, see #983. CHANGELOG and this PR sounds like yapf now fully supports python 3.10, but it's indeed not the case yet...

**Comment by daskol** [comment]
Could you add a release tag e.g 0.33.0. I guess that support to Python 3.10 is weighty reason to make a release. Also, there are no updates for package in Linux distros because there is no release. 

P.S. I'd like to express my support to request #1001.

**Pull request merged**
