### PR TITLE
"YAPF inserts weird long breaks in function call" fix

### PR DESCRIPTION
**Pull request by jbrill**
This fix required simply a change in conditional logic regarding MustSplit() in format_decision_state.py

I've added two unit tests as well in reformatter_basic_test.py to encompass the two example tests provided by @alanhdu in issue #544

### CODE REVIEW

**Comment by mnsaab** [comment]
@gwelymernans Hey Bill, Jason and I both have the CLAs signed for our respective emails connected to these github accounts. However, the Googlebot keeps saying that we failed. Any ideas why?

**Comment by gwelymernans** [comment]
Weird. I checked with the database and it showed that you have signed it. It must just be an oversight.

**Comment by gwelymernans** [comment]
Oh yeah, you will want to run YAPF on the YAPF codebase (that's why the travis-ci check is failing).

```shell
python -m yapf -r -i .
```

**Comment by jbrill** [comment]
Thanks! Seems to still be failing when SCA=True environmental variables are set. I’ll definitely dig deeper into my own changes as well to encompass the original logic.

-Jason

**Comment by keis** [comment]
I'm running into the same issue trying out yapf, are you still working on this @jbrill?

**Pull request closed without merging**
