### PR TITLE
Make CI enforce pre-commit clean code

### LINKED ISSUE #1081: Enforce pre-commit clean code via CI?
Hi!

I'm considering to provide a pull request that enforces pre-commit clean CI because `main` is not pre-commit clean today and CI would prevent that from happening again. For that pull request to be healthy:
- pre-commit files would have ideally gone down to a single copy already (issue #1077) at that point
- Pull requests #1078, #1079, #1080 would ideally have been merged already
- It would need to be decided if (or when) mass-applying yapf to itself is considered tolerable with the current set of open pull requests around.

What do you think?

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #1081

Let me know what you think :beers: 

CC @bwendling @Spitfire1900 @thiagowfx

### CODE REVIEW

**Comment by thiagowfx** [comment]
If you split the PR into two, I am happy to approve the smaller one with `.github/workflows/ci.yml` and `.pre-commit-config.yaml`, they look great by moving the logic to pre-commit.

For the other two files, I don't have bandwidth to review them at the moment

**Comment by hartwork** [comment]
@thiagowfx sounds fair, let me split off the `pre-commit-autoupdate.yml` part, one minute.

**Comment by hartwork** [comment]
@thiagowfx done, what do you think?

**Comment by thiagowfx** [comment]
I had meant without the `.github/workflows/pre-commit.yml` file as well...but, it looks OK, so you can keep it.

Could you also add a badge for the pre-commit workflow to the README.md?

**Review by thiagowfx — APPROVED** [review]

**Comment by hartwork** [comment]
> I had meant without the `.github/workflows/pre-commit.yml` file as well...but, it looks OK, so you can keep it.

@thiagowfx cool!


> Could you also add a badge for the pre-commit workflow to the README.md?

Sure, done.

**Comment by Spitfire1900** [comment]
I have an open PR for pypa/pipx#981.

What are your thought if instead of this PR's implementation and #1097 something like the following was the content in `.pre-commit-config.yaml`? This would automatically use the latest GA release from PyPi anytime the job is run.

```yaml
repos:
  - repo: https://github.com/Spitfire1900/pipx
    rev: 9e59f26
    hooks:
    - id: pipx
      alias: yapf
      name: yapf
      args: ['isort', '--filter-files']
      types: ['python']
  - repo: https://github.com/Spitfire1900/pipx
    rev: 9e59f26
    hooks:
    - id: pipx
      alias: yapf
      name: yapf
      args: ['isort', '--filter-files']
      types: ['python']
  - repo: https://github.com/Spitfire1900/pipx
    rev: 9e59f26
    hooks:
      - id: pipx
        alias: flake8
        name: flake8
        args: ['flake8']
        types: ['python']
```

**Review by Spitfire1900 — APPROVED** [review]

**Comment by hartwork** [comment]
@Spitfire1900 I'm not a fan honestly, because ideally I want the hardest pinning possible plus pull request updates for good maximum security and good CI stability: controlled movement. Free movement gives neither of these.

**Review by thiagowfx — APPROVED** [review]

**Comment by hartwork** [comment]
@thiagowfx thanks! :pray:

**Pull request merged**
