### PR TITLE
pyproject.toml updates to HACKING.md

### PR DESCRIPTION
**Pull request by Spitfire1900**
* Setup module is missing, use build instead.
* Run tests with tox.

### CODE REVIEW

**Comment by Spitfire1900** [comment]
@bwendling after this is merged in I think we're in a good spot to release 0.41.0

**Comment by bwendling** [comment]
Could you add example commands for each step?

**Comment by bwendling** [comment]
Yeah, something like that would be fine.

**Comment by Spitfire1900** [comment]
@bwendling I've updated `HACKING.md` and I've confirmed that this works on both Ubuntu 22.04 and Windows 10.

**Review by bwendling — APPROVED** [review]

**Pull request merged**
