### PR TITLE
Add documentation about --diff return code

### PR DESCRIPTION
**Pull request by mst-ableton**
Didn't see any documentation on here about the return code, and hoped to save time for other people looking to accomplish the same thing. Let me know if there's a better place in the doc to put this.

### CODE REVIEW

**Comment by gwelymernans** [comment]
Thanks! Though maybe instead of making this one of the FAQs, we should have something further up that indicates what the return values are in different situations and what they mean. Maybe in the `Usage` section? What do you think?

**Comment by mst-ableton** [comment]
Sure, that sounds reasonable. I'll make an edit in a bit.

**Comment by mst-ableton** [comment]
@gwelymernans ok, let me know if this is more to your liking!

**Comment by gwelymernans** [comment]
Thank you!

**Pull request merged**
