### PR TITLE
Added pyproject extra to install toml package as an optional dependency

### PR DESCRIPTION
**Pull request by arareko**
This patch fixes https://github.com/google/yapf/issues/936

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 Should be marked as an optional dependency.

**Comment by arareko** [comment]
> 👎 Should be marked as an optional dependency.

@GrahamCampbell not optional when it is being used directly in one of the YAPF modules.

**Comment by GrahamCampbell** [comment]
The code expects it to be missing and handles that case. Totally not the same as just straight up importing it.

**Comment by gwelymernans** [comment]
I have to agree with @GrahamCampbell here.

**Comment by dzshn** [comment]
I think this change is reasonable considering `pyproject.toml` is becoming standard for declaring build systems, but also what mentioned in #936.. or at least I do find it unusual to have to add `toml` as a dep myself when using poetry with yapf

**Comment by arareko** [comment]
@gwelymernans I have made the necessary adjustments.

**Comment by pedro757** [comment]
Question: why toml can not just be a normal dependency?

I mean, in the end **yapf** is just a **developer dependency** it actually wont affect any program performance.

**Comment by pfernandesviz** [comment]
Can you guys merge this?

**Comment by gwelymernans** [comment]
Sorry about the lateness. Done.

**Pull request merged**
