### PR TITLE
Do not match keywords named 'match'

### LINKED ISSUE #1110: [0.40.0] Mistakes variable "match" for a match statement?
Hi! :wave: 

Yapf 0.40.0 suggests this change in formatting at https://github.com/hartwork/wnpp.debian.net/actions/runs/5299147736/jobs/9591931423?pr=707#step:6:30 …

```diff
--- a/wnpp_debian_net/management/commands/importdebbugs.py
+++ b/wnpp_debian_net/management/commands/importdebbugs.py
@@ -235,8 +235,8 @@ class Command(ReportingMixin, BaseCommand):
     @staticmethod
     def _parse_wnpp_issue_subject(subject) -> tuple[str, str, str]:
         match = re.match(
-            '^(?:[Ss]ubject: )?(?P<kind>[A-Z]{1,3}): ?(?P<package>[^ ]+)(?:(?: --| -| —|:) (?P<description>.*))?$',
-            subject)
+                '^(?:[Ss]ubject: )?(?P<kind>[A-Z]{1,3}): ?(?P<package>[^ ]+)(?:(?: --| -| —|:) (?P<description>.*))?$',
+                subject)
         if match is None:
             raise _MalformedSubject(f'Malformed subject {subject!r}')
```

… which now indents by one level more than expected. I'm reading that as the variable "match" name being misinterpreted as a match statement. I could imagine this will be hard to fix. What do you think?

Best, Sebastian

### PR DESCRIPTION
**Pull request by Spitfire1900**
Closes #1110 , do not match variable names named 'match'.

### CODE REVIEW

**Comment by Spitfire1900** [comment]
I've verified locally that the diff is clean.

```shell
:~/Repos/yapf/wt/1110$ curl https://raw.githubusercontent.com/hartwork/wnpp.debian.net/master/wnpp_debian_net/management/commands/importdebbugs.py > importdebbugs.py \
&& curl https://raw.githubusercontent.com/hartwork/wnpp.debian.net/master/.style.yapf > ..style.yapf \
&& pipx run --spec=. yapf --style ..style.yapf --diff importdebbugs.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15430  100 15430    0     0  40814      0 --:--:-- --:--:-- --:--:-- 40820
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   126  100   126    0     0    989      0 --:--:-- --:--:-- --:--:--   992
⚠️  yapf is already on your PATH and installed at /home/kyle/.local/bin/yapf. Downloading and running anyway.
kyle@mainstay:~/Repos/yapf/wt/1110$
```

@hartwork , can you propose a test for this case?

**Comment by hartwork** [comment]
@Spitfire1900 did you see https://github.com/hartwork/wnpp.debian.net/commit/0a49666a965b7345f2baa87cd855cf50212520fb ?

**Comment by Spitfire1900** [comment]
> @Spitfire1900 did you see https://github.com/hartwork/wnpp.debian.net/commit/0a49666a965b7345f2baa87cd855cf50212520fb ? 

I'll try adding it later, @ mentioned yourself because I wasn't going to be available until tomorrows to complete this PR.

**Comment by char101** [comment]
Minimal test case

```python
match = (
    1,
    2,
)
```

Without the fix
```
..\env\scripts\python -m yapf -d ..\test.py
--- ..\test.py  (original)
+++ ..\test.py  (reformatted)
@@ -1,4 +1,4 @@
 match = (
-    1,
-    2,
+        1,
+        2,
 )
```

**Comment by Spitfire1900** [comment]
The sample test added with [this commit](https://github.com/google/yapf/pull/1111/commits/e579d1e19ee6da2e4c885691f0026ff9ceaa0ce7) passes on both tag v0.40.1 and this branch, at this time I am unsure why. The attached file generates the expected output below on v0.40.1 and no output on this branch.
[matchtest.py.txt](https://github.com/google/yapf/files/12137953/matchtest.py.txt)

```diff
 pipx run yapf==0.40.1 --no-local-style --diff matchtest.py 
⚠️  yapf is already on your PATH and installed at /home/kyle/Repos/yapf/wt/1110/.venv/bin/yapf. Downloading and running anyway.
--- matchtest.py        (original)
+++ matchtest.py        (reformatted)
@@ -4,11 +4,11 @@
 @staticmethod
 def _parse_wnpp_issue_subject(subject) -> tuple[str, str, str]:
     match = re.match(
-        '^(?:[Ss]ubject: )?(?P<kind>[A-Z]{1,3}): ?(?P<package>[^ ]+)(?:(?: --| -| —|:) (?P<description>.*))?$',
-        subject)
+            '^(?:[Ss]ubject: )?(?P<kind>[A-Z]{1,3}): ?(?P<package>[^ ]+)(?:(?: --| -| —|:) (?P<description>.*))?$',
+            subject)
 
 
 match = (
-    1,
-    2,
+        1,
+        2,
 )
 ```

**Comment by Spitfire1900** [comment]
@bwendling do you have any input on why the manual test referenced in https://github.com/google/yapf/pull/1111#issuecomment-1646737716 performs as expected but the pytest test does not?

**Comment by bwendling** [comment]
> @bwendling do you have any input on why the manual test referenced in [#1111 (comment)](https://github.com/google/yapf/pull/1111#issuecomment-1646737716) performs as expected but the pytest test does not?

@Spitfire1900 I don't. Just checking. The diff in [this comment](https://github.com/google/yapf/pull/1111#issuecomment-1646737716) is wrong and the behavior of `matchtest.py` is right?

**Comment by bwendling** [comment]
Ah! I see. The problem is probably in `_GetNewlineColumn`. My guess is that the code that would call `_IsCompoundStmt` isn't being executed for some reason or another. Maybe having to do with the `style`?

**Comment by Spitfire1900** [comment]
So I was unable to get a test to perform as expected, so I am proposing this PR without a test case.

**Comment by Spitfire1900** [comment]
@bwendling is it okay if this is merged without new tests?

**Comment by bwendling** [comment]
Sure! Thanks. :-)

**Pull request merged**
