### PR TITLE
pypi: include missing `Grammar.txt` and `PatternGrammar.txt`

### LINKED ISSUE #1107: PyPI package is missing Grammar.txt
```
yapf --help

FileNotFoundError: [Errno 2] No such file or directory: '/MY/PATH/lib/python3.11/site-packages/yapf_third_party/_ylib2to3/Grammar.txt'
```

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #1107

relates to https://github.com/Homebrew/homebrew-core/pull/133505

### CODE REVIEW

**Comment by Spitfire1900** [comment]
Running `python -m setup bdist_wheel` works on my machine, why is this required in `MANIFEST.in` here? Shouldn't https://github.com/google/yapf/blob/f4a7bb4a082bb35a3bf3b8d521b68d3b9072a27d/setup.py#L87-L94 take care of this? 

Repro env:
python 3.10.6
setuptools==67.7.2
wheel==0.40.0

**Comment by Spitfire1900** [comment]
@bwendling high priority triage for this PR.

**Review by Spitfire1900 — APPROVED** [review]
Please include LICENSE files also.

**Review by Spitfire1900 — CHANGES_REQUESTED** [review]
Write tests to reproduce error condition.

**Comment by char101** [comment]
Is this still apply https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distutils ?

`package_data` is only applied to binary dist, in this case adding it in `manifest.in` seems the right path.

**Comment by hartwork** [comment]
> side note, this is still needed for [0.40.1 release](https://github.com/Homebrew/homebrew-core/pull/134253)

Potentially not, please see comment https://github.com/google/yapf/issues/1107#issuecomment-1599098138

**Comment by hartwork** [comment]
Maybe the real fix is adding `setup_requires=['setuptools>=VERSION']` to the call to `setuptools.setup` in file `setup.py`?

**Comment by chenrui333** [comment]
The two files were definitely missing in the 0.40.0 rel (you can untar [this sdit file](https://files.pythonhosted.org/packages/7a/cb/7675e1d2788ce93246f8c2e0e6ed00019c86853f92dc9226a90e0e1a1e95/yapf-0.40.0.tar.gz)), but now got included in the 0.40.1 rel, let me check with my build in a bit :)

**Comment by hartwork** [comment]
> The two files were definitely missing in the 0.40.0 rel (you can untar [this sdit file](https://files.pythonhosted.org/packages/7a/cb/7675e1d2788ce93246f8c2e0e6ed00019c86853f92dc9226a90e0e1a1e95/yapf-0.40.0.tar.gz)), but now got included in the 0.40.1 rel

@chenrui333 no doubt about that, I confirmed at https://github.com/google/yapf/issues/1107#issuecomment-1598713818 in detail.

**Comment by chenrui333** [comment]
Looks like we have sorted on this (the new version bump works fine on the homebrew side without the patch work), I am going to close this PR. Thanks @hartwork!

**Comment by chenrui333** [comment]
> Please include LICENSE files also.

Now the two LICENSE files are all included in the 0.40.1 rel

```diff
+	third_party/yapf_third_party/_ylib2to3/Grammar.txt
+	third_party/yapf_third_party/_ylib2to3/LICENSE
+	third_party/yapf_third_party/_ylib2to3/PatternGrammar.txt
+	third_party/yapf_third_party/yapf_diff/LICENSE
```

**Comment by hartwork** [comment]
> Maybe the real fix is adding `setup_requires=['setuptools>=SOME_VERSION_HERE']` to the call to `setuptools.setup` in file `setup.py`?

Went for that approach in #1115 now.

**Pull request closed without merging**
