### PR TITLE
make sure input files are '.py' ended

### PR DESCRIPTION
**Pull request by AmeenAli**
make sure input files are python files

### CODE REVIEW

**Comment by gwelymernans** [comment]
Is there a use case where not haven't this check caused a problem?

**Comment by AmeenAli** [comment]
i don't even know why there is a problem! @gwelymernans

**Comment by gwelymernans** [comment]
?? I don't understand what you're saying. At the moment, there isn't an issue with reformatting files that use Python syntax but don't have a `.py` extension. I don't think this PR is necessary.

**Comment by AmeenAli** [comment]
what about files that does not have python syntax? @gwelymernans

**Comment by gwelymernans** [comment]
There are two scenarios:

1. The files are explicitly listed on the command-line:

    ```shell
    python -m yapf file1
    ```

    In this case, we will process the files no matter what extension they have.

2. Recursive mode. In this case, we process files with a `.py` extension.

So there's really no need to reject any files that don't have that extension...

**Pull request closed without merging**
