### PR TITLE
SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES and FORCE_MULTILINE_DICT interaction

### PR DESCRIPTION
**Pull request by ManiacDC**
* explicitly defined FORCE_MULTILINE_DICT to override SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES
* added tests to account for the interaction of these two knobs

This is a fix for #833 . This specifically fixes FORCE_MULTILINE_DICT. I think the more correct solution is actually to change this code:
```
      # Allow the fallthrough code to handle the closing bracket.
      if current != opening.matching_bracket:
        # If the container doesn't fit in the current line, must split
        return not self._ContainerFitsOnStartLine(opening)
```

to
```
      # Allow the fallthrough code to handle the closing bracket.
      if current != opening.matching_bracket:
        # If the container doesn't fit in the current line, must split
        if not self._ContainerFitsOnStartLine(opening):
          return True
```

But that is a much more far-reaching change and would change the behavior of existing defaults.

### CODE REVIEW

**Comment by ManiacDC** [comment]
CLA fixed, wrong author was on the commit.

**Comment by dtczest** [comment]
Fixed formatting (and CLA, again)

**Comment by ManiacDC** [comment]
Hello, is someone able to run the workflows for this PR? Thanks!

**Comment by bwendling** [comment]
Sorry about the delay. Please add a comment in the CHANGELOG file.

**Comment by ManiacDC** [comment]
@bwendling I've updated the CHANGELOG

**Comment by ManiacDC** [comment]
Thank you @bwendling !

**Pull request merged**
