### PR TITLE
Added support for tab indentation

### PR DESCRIPTION
**Pull request by dracony**
Original issue:
https://github.com/google/yapf/issues/244

### CODE REVIEW

**Comment by dracony** [comment]
I signed it

**Comment by gwelymernans** [comment]
Thank you! Please update the `README.rst` and `CHANGELOG` files and "squash" them into this commit.

**Comment by dracony** [comment]
done =)

**Comment by gwelymernans** [comment]
One last thing. It looks like there are some test failures re formatting:

https://travis-ci.org/google/yapf/jobs/135383112

**Comment by dracony** [comment]
Ah, so it was formatting that was causing the failure. Fixed =)

**Comment by dracony** [comment]
Cool, Thanks!

**Pull request merged**
