### PR TITLE
PR for #308, all tests passed

### PR DESCRIPTION
**Pull request by rojaster**
This is PR for issue #308  in dev branch, I've changed some tests just adding setUp to them that encapsulate style for each test case. 
I have other fixes and improvements, but I am testing it still

### CODE REVIEW

**Comment by gwelymernans** [comment]
Thank you! Could you squash the changes into one? It'll be easier to review them.

**Comment by rojaster** [comment]
@gwelymernans Ok

**Comment by rojaster** [comment]
This occurred because I missed .editorconfig at fist time when I had opened yapf in IDE. And when I had started development I applied its configuration.

**Comment by rojaster** [comment]
current changes are not consistent with the current version. Bug patched as a hack.

**Pull request closed without merging**
