### PR TITLE
Fix pickle related race condition (fixes #1164, fixes #1204)

### LINKED ISSUE #1164: Grammar caching causes EOFError and race condition when used as pre-commit hook
Thanks to [pre-commit#851](https://github.com/pre-commit/pre-commit/pull/851/files), hooks can now be executed in parallel for each file. This feature is enabled by default.

When a large number of files need to be formatted at once, this concurrency introduces a race condition in  wherein one process can [conclude that the pickled grammar file does not exist](https://github.com/google/yapf/blob/febc496a5653e1ed8f875e7e0bfff8513697c24a/third_party/yapf_third_party/_ylib2to3/pgen2/driver.py#L226) and [start to create it](https://github.com/google/yapf/blob/febc496a5653e1ed8f875e7e0bfff8513697c24a/third_party/yapf_third_party/_ylib2to3/pgen2/driver.py#L242). Meanwhile, another process sees the newly created pickle file before it is done being written, concludes that it is newer than the raw unpickled grammar, and then [attempts to load it](https://github.com/google/yapf/blob/febc496a5653e1ed8f875e7e0bfff8513697c24a/third_party/yapf_third_party/_ylib2to3/pgen2/driver.py#L248).
The result is the following stack trace:
```
Traceback (most recent call last):
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/bin/yapf", line 5, in <module>
    from yapf import run_main
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf/__init__.py", line 41, in <module>
    from yapf.yapflib import yapf_api
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf/yapflib/yapf_api.py", line 38, in <module>
    from yapf.pyparser import pyparser
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf/pyparser/pyparser.py", line 44, in <module>
    from yapf.yapflib import format_token
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf/yapflib/format_token.py", line 23, in <module>
    from yapf.pytree import pytree_utils
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf/pytree/pytree_utils.py", line 30, in <module>
    from yapf_third_party._ylib2to3 import pygram
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf_third_party/_ylib2to3/pygram.py", line 29, in <module>
    python_grammar = driver.load_grammar(_GRAMMAR_FILE)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 252, in load_grammar
    g.load(gp)
  File "~/.cache/pre-commit/repo73fphdkg/py_env-python3.11/lib/python3.11/site-packages/yapf_third_party/_ylib2to3/pgen2/grammar.py", line 95, in load
    d = pickle.load(f)
        ^^^^^^^^^^^^^^
EOFError: Ran out of input
```
Since the process writing the file is not impacted by this error, the pickled grammar will get cached. Thus, subsequent runs will succeed. However, if one is using `yapf` in a continuous integration context, this would cause a failed pipeline with potentially high probability (depending on the number of files) with no obvious recourse.

A workaround is to add `require_serial` to the `yapf` hook in your project's `.pre-commit-config.yaml`, but this comes at the cost of losing the advantages of [pre-commit#851](https://github.com/pre-commit/pre-commit/pull/851/files). I believe the logic in [`_load_grammar`](https://github.com/google/yapf/blob/febc496a5653e1ed8f875e7e0bfff8513697c24a/third_party/yapf_third_party/_ylib2to3/pgen2/driver.py#L214) could be refactored to avoid the race condition with some more careful checks.

### LINKED ISSUE #1204: [Bug] [Crash][Reproducible] `EOFError: Ran out of input` when import yapf with multiprocess
> previous similar issue #1164 

## Problems
- When i use yapf (just import it) in multiprocess program, it will crash with 'EOFError: Ran out of inpu'，log info below:

image

## Reproduction
1. yapf==0.40.2
2. `rm -r ~/.cache/YAPF`
3. run this python code:
```
 import multiprocessing
 
 def proc():
     import yapf
 
 if __name__ == "__main__":
     pp=[]
     for i in range(100):
         p = multiprocessing.Process(target=proc)
         pp.append(p)
 
     for p in pp:
         p.start()
 
     for p in pp:
         p.join()
                                                   
```

## Reason
the problem code is here:https://github.com/google/yapf/blob/c0908d043b45f082e6339cd767c28e6d697cb22e/third_party/yapf_third_party/_ylib2to3/pgen2/driver.py#L247

When in multi process enviroment,some process will create grammar cache(when ~/.cache/YAPF not exists), before the process write to the cache file, other process will see the file exist and load it, but the cache file is empty right now , so `EOFError` will raise and the program crashed.

## How to fix it?

- I think we need to add `try` here(https://github.com/google/yapf/blob/c0908d043b45f082e6339cd767c28e6d697cb22e/third_party/yapf_third_party/_ylib2to3/pgen2/driver.py#L247) like we had add `try` when we create the cache.
- Or we can add a  multiprocess.Lock here
- Or we can do `python -c 'import yapf'` before we start our multiprocess program.(for users,trick)

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #1164
Fixes #1204

I have flaky pre-commit CI caused by Yapf in multiple repositories by now and it was about time to start doing something about it… I'm grateful for the great analysis by both @a-gardner1 and @whlook.

~The pull request sits on top of #1242 for the moment purely for a chance at a green CI: I'm happy to rebase off of it after that one has been merged.~

For a convenient reproducer of the race condition based on earlier work by @whlook please see https://github.com/google/yapf/issues/1204#issuecomment-2391417931 .

If this could be reviewed and merged soon-ish, that would rock the house. Thanks in advance! :pray: 

CC @bwendling @whlook @a-gardner1 @kamahen

### CODE REVIEW

**Comment by a-gardner1** [comment]
Looks good to me. Thanks for picking it up! Do you think a unit test could be added to verify that the reproducer is fixed and does not regress in the future?

**Comment by hartwork** [comment]
> Looks good to me. Thanks for picking it up! Do you think a unit test could be added to verify that the reproducer is fixed and does not regress in the future?

@a-gardner1 that's an interesting idea. I'm happy to add a test based on that reproducer once it's the last thing considered blocking a merge.

**Comment by hartwork** [comment]
> I'm happy to rebase off of it after that one has been merged.

Done.

**Comment by hartwork** [comment]
@bwendling any chance you could review the fix this coming weak? The bug is quite a bummer and I'm happy to make adjustments where needed. Thank you! :pray:

**Review by bwendling — APPROVED** [review]

**Comment by hartwork** [comment]
@bwendling many thanks for the review and merge! Is there a chance for a new release v0.40.3 include this pull request to get the fixes to the users? Please let me know if you could use any help on that end :pray:

**Pull request merged**
