### PR TITLE
Add yapf entry point to setup.py

### LINKED ISSUE #6: Use entrypoints in setup.py to create a command
This will create a clean command line tool in any OS : http://stackoverflow.com/questions/774824/explain-python-entry-points

### PR DESCRIPTION
**Pull request by Frozenball**
closes #6

### CODE REVIEW

**Comment by gmr** [comment]
+1

**Comment by berkerpeksag** [comment]
Since `entry_points` is a setuptools thing, you also will need to change the `distutils.core` import to setuptools.

**Comment by nils-werner** [comment]
+1, wanted to implement this myself :-)

**Comment by nils-werner** [comment]
This PR should update `README.md` and reference to the new `yapf` executable instead of `DIR/yapf`.

**Comment by gwelymernans** [comment]
Thanks, Frozenball. Could you make sure to sign the Google CLA? See the "CONTRIBUTING.rst" file for information on how to do that. :-)

**Comment by Frozenball** [comment]
Sure.

**Comment by basicinside** [comment]
:+1:, also was about to implement it myself. Luckily I checked the PRs. Thanks frozenball.

**Comment by gwelymernans** [comment]
Ping for signing the CLA. :-)

**Comment by Frozenball** [comment]
I have already signed the CLA for two email addresses. I'm not sure what the "unable to verify author consent" means in this case.

**Comment by gwelymernans** [comment]
The bot's now happy. :-) Thank you!

**Pull request merged**
