### PR TITLE
Make yapf pip installable

### PR DESCRIPTION
**Pull request by di**
Depends on https://github.com/google/yapf/pull/7

https://pypi.python.org/pypi/yapf

### CODE REVIEW

**Comment by gwelymernans** [comment]
Could you update the README.rst file to the new way of installing yapf? :-)

**Comment by di** [comment]
@googlebot I authored these commits. You're probably confused by my github@... address. :-)

**Comment by eliben** [comment]
@di Please always squash your pull requests into a single commit

**Comment by eliben** [comment]
Thanks for the contribution, @di. YAPF is not on PyPI yet, and we definitely plan to put it there at some point. Right now, we're considering it an alpha release and want to stabilize a tool a bit more before we feel confident enough publishing it outside Github.

Bill will talk about YAPF at PyCon in a couple of weeks, and we plan to have an initial release up on PyPI by that time.

**Comment by eliben** [comment]
@di could you please delete the package from PyPI -- you uploaded it there and now you're its owner -- we'd like to reclaim that, if possible.

**Comment by di** [comment]
@eliben Yeah no problem! I took the release down. Let me know what username to transfer the package to.

**Comment by eliben** [comment]
@di Thank you. Please transfer it to eliben@

**Comment by di** [comment]
@eliben Done.

**Comment by santagada** [comment]
now this can be merged right?

**Comment by gwelymernans** [comment]
Leonardo, I would like to wait until next week to do that. We're still in
the middle of getting YAPF to be semi-stable, so there is a lot of flux in
the code base, and I don't want to keep releasing tons of versions when
things change. :-)

**Comment by hayd** [comment]
@gwelymernans You should register on pypi, even if you don't upload yet.

**Comment by gwelymernans** [comment]
@eliben has that covered. :-)

**Comment by eliben** [comment]
yapf is on PyPI now. I'm closing this - similar contents made it into the README.

**Pull request closed without merging**
