### PR TITLE
Add minimal tox.ini file

### PR DESCRIPTION
**Pull request by hayd**

### CODE REVIEW

**Comment by eliben** [comment]
Please squash all pull requests into a single commit

**Comment by hayd** [comment]
These two commits are independent.

**Comment by eliben** [comment]
@hayd Ah I see. Thanks for clarifying. If that's the case, please split them to two separate pull requests.

It's vastly easier to manage history and pull requests if each one has a single commit addressing a single issue.

**Comment by hayd** [comment]
Will blast the second (2 line) commit when I get home.

Perhaps it's worth including this in CONTRIBUTING.rst (single commit PRs).

**Comment by hayd** [comment]
Removed https://github.com/hayd/yapf/commit/17b5945.

**Comment by gwelymernans** [comment]
@hayd I'm not familiar with `tox.ini`. Could you explain what it does? :-)

**Comment by hayd** [comment]
@gwelymernans This is a [tox](https://tox.readthedocs.org/en/latest/) configuration file, it's similar to the `.travis.yml` but runs locally... If you run tox (assuming it's correctly installed) in the yapf directory then for each env in the envlist it'll:

- set up environment
- install the dependencies (though yapf doesn't have any)
- install yapf
- run the test suite

That is, if you have this tox.ini then `tox` will run the tests on python 2.7 and 3.4.

**Comment by gwelymernans** [comment]
Ah! Okay, that sounds good.

**Pull request merged**
