### PR TITLE
Fix edge case of python file which is blank lines.

### PR DESCRIPTION
**Pull request by hayd**
Before this was just passed through (no diff was shown, nothing happened inplace).

See https://github.com/google/yapf/pull/120#issuecomment-95316601.

### CODE REVIEW

**Comment by hayd** [comment]
Not clear to me why this fails on python 2. :(

**Comment by gwelymernans** [comment]
I think the reason why is because it looks like an empty string is considered a `str` in Python 2.7. If I wrap it with `unicode`, then it works. It's probably because of the encoding that the file is opened with.

**Comment by hayd** [comment]
@gwelymernans But the error is:

    AssertionError: u'' != u'\n'

?

**Comment by gwelymernans** [comment]
Ah! I see. I'm not sure what to say. Try printing out values right before it writes to the file?

**Comment by hayd** [comment]
Ha! python 2 was sensitive about unicode. One line fix...

*Strangely the raised exception was not the reported fail.*

**Pull request merged**
